
#change this to your arduino program folder
ARDUINO_DIR = /usr/share/arduino

#your arduino device, usually /dev/ttyACM0
ARDUINO_PORT = /dev/ttyACM*

#change this to the location of your arduino libraries
USER_LIB_PATH = /usr/share/arduino/libraries

#change this to your arduino model
BOARD_TAG = uno

#change this to the location of your Arduino.mk file
include /usr/share/arduino/Arduino.mk
